name: Benchmark OpenCV on RISC-V

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: opencv

    - name: Install prerequisities
      run: |
          python3 -m pip install gdown
          gdown https://drive.google.com/uc?id=1dww_ZMX68nTf5UmlDzDN3fJy4yLr2i4u
          tar -xf sc-dt-2024.09.tar.gz
          sudo cp -r sc-dt/riscv-gcc /opt/riscv
          sudo cp -r sc-dt/llvm /opt/rvv-llvm

    - name: Cross-compile OpenCV
      run: |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=$(realpath opencv/platforms/linux/riscv64-clang.toolchain.cmake) \
          -DRISCV_RVV_SCALABLE=ON \
          -DWITH_OPENCL=OFF \
          -DCPU_BASELINE_REQUIRE=RVV \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_LIST=ts,core \
          -S opencv -B opencv_build

        cmake --build opencv_build -j$(nproc --all)

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: opencv_build
        path: |
          opencv/modules/ts/misc/summary.py
          opencv_build/bin/*
          opencv_build/lib/*

  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: opencv_build

    - name: Run performance tests
      run: |
        export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
        chmod +x ./bin/*
        ./bin/opencv_perf_core --gtest_output=xml:pr.xml --gtest_filter=*minMaxLoc*
        ./bin/opencv_perf_core --gtest_output=xml:pr2.xml --gtest_filter=*minMaxLoc*
        python3 summary.py pr.xml pr2.xml
