name: Benchmark OpenCV on RISC-V

on: [pull_request]

jobs:
  build_with_gcc:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install prerequisities
      run: |
          python3 -m pip install gdown
          gdown https://drive.google.com/uc?id=1dww_ZMX68nTf5UmlDzDN3fJy4yLr2i4u
          tar -xf sc-dt-2024.09.tar.gz
          sudo mkdir /opt/riscv
          sudo mkdir /opt/rvv-llvm
          sudo cp -r sc-dt/riscv-gcc/* /opt/riscv
          sudo cp -r sc-dt/llvm/* /opt/rvv-llvm

    - name: Cross-compile OpenCV
      run: |
        mkdir opencv_build && cd opencv_build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$(realpath ../platforms/linux/riscv64-clang.toolchain.cmake) \
          -DRISCV_RVV_SCALABLE=ON \
          -DCPU_BASELINE_REQUIRE=RVV \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_LIST=ts,core

        cmake --build . -j$(nproc --all)
